/*
 * This file is generated by jOOQ.
 */
package com.sunnymix.graphviews.orm.jooq;


import com.sunnymix.graphviews.orm.jooq.tables.Graph;
import com.sunnymix.graphviews.orm.jooq.tables.records.GraphRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * graphviews.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<GraphRecord> KEY_GRAPH_PRIMARY = Internal.createUniqueKey(Graph.GRAPH, DSL.name("KEY_graph_PRIMARY"), new TableField[] { Graph.GRAPH.ID }, true);
}
