/*
 * This file is generated by jOOQ.
 */
package com.sunnymix.graphviews.orm.jooq;


import com.sunnymix.graphviews.orm.jooq.tables.Graph;


/**
 * Convenience access to all tables in graphviews.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>graphviews.graph</code>.
     */
    public static final Graph GRAPH = Graph.GRAPH;
}
