/*
 * This file is generated by jOOQ.
 */
package com.sunnymix.graphviews.orm.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Graph implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String         id;
    private final String         title;
    private final String         text;
    private final OffsetDateTime created;

    public Graph(Graph value) {
        this.id = value.id;
        this.title = value.title;
        this.text = value.text;
        this.created = value.created;
    }

    public Graph(
        String         id,
        String         title,
        String         text,
        OffsetDateTime created
    ) {
        this.id = id;
        this.title = title;
        this.text = text;
        this.created = created;
    }

    /**
     * Getter for <code>graphviews.graph.id</code>. ID
     */
    public String getId() {
        return this.id;
    }

    /**
     * Getter for <code>graphviews.graph.title</code>. 标题
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Getter for <code>graphviews.graph.text</code>. 文本
     */
    public String getText() {
        return this.text;
    }

    /**
     * Getter for <code>graphviews.graph.created</code>. 创建时间
     */
    public OffsetDateTime getCreated() {
        return this.created;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Graph (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(text);
        sb.append(", ").append(created);

        sb.append(")");
        return sb.toString();
    }
}
